CREATE TABLE IF NOT EXISTS historical_quality_daily (
  audit_run_id TEXT NOT NULL,
  collection_date TEXT NOT NULL,
  scope TEXT NOT NULL CHECK (scope IN ('overall', 'home_loans', 'savings', 'term_deposits')),
  row_count INTEGER NOT NULL DEFAULT 0,
  bank_count INTEGER NOT NULL DEFAULT 0,
  product_count INTEGER NOT NULL DEFAULT 0,
  series_count INTEGER NOT NULL DEFAULT 0,
  active_series_count INTEGER NOT NULL DEFAULT 0,
  changed_series_count INTEGER NOT NULL DEFAULT 0,
  provenance_exact_count INTEGER NOT NULL DEFAULT 0,
  provenance_reconstructed_count INTEGER NOT NULL DEFAULT 0,
  provenance_legacy_count INTEGER NOT NULL DEFAULT 0,
  provenance_quarantined_count INTEGER NOT NULL DEFAULT 0,
  provenance_unclassified_count INTEGER NOT NULL DEFAULT 0,
  duplicate_rows INTEGER NOT NULL DEFAULT 0,
  missing_required_rows INTEGER NOT NULL DEFAULT 0,
  invalid_value_rows INTEGER NOT NULL DEFAULT 0,
  cross_table_conflict_rows INTEGER NOT NULL DEFAULT 0,
  explained_appearances INTEGER NOT NULL DEFAULT 0,
  unexplained_appearances INTEGER NOT NULL DEFAULT 0,
  explained_disappearances INTEGER NOT NULL DEFAULT 0,
  unexplained_disappearances INTEGER NOT NULL DEFAULT 0,
  baseline_bank_count REAL,
  baseline_product_count REAL,
  baseline_series_count REAL,
  baseline_confidence TEXT NOT NULL DEFAULT 'high' CHECK (baseline_confidence IN ('high', 'bootstrap_forward', 'low')),
  raw_run_state_present INTEGER NOT NULL DEFAULT 0 CHECK (raw_run_state_present IN (0, 1)),
  permanent_evidence_present INTEGER NOT NULL DEFAULT 1 CHECK (permanent_evidence_present IN (0, 1)),
  raw_run_state_expected INTEGER NOT NULL DEFAULT 0 CHECK (raw_run_state_expected IN (0, 1)),
  uniqueness_score REAL,
  required_field_score REAL,
  domain_validity_score REAL,
  cross_table_consistency_score REAL,
  structural_score_v1 REAL,
  provenance_score_v1 REAL,
  bank_count_score REAL,
  product_count_score REAL,
  series_count_score REAL,
  coverage_score_v1 REAL,
  anomaly_pressure_score_v1 REAL,
  intra_day_score_v1 REAL,
  continuity_score_v1 REAL,
  count_stability_score_v1 REAL,
  rate_flow_score_v1 REAL,
  transition_score_v1 REAL,
  run_state_observability_score REAL,
  evidence_confidence_score_v1 REAL,
  metrics_json TEXT NOT NULL DEFAULT '{}',
  evidence_json TEXT NOT NULL DEFAULT '{}',
  PRIMARY KEY (audit_run_id, collection_date, scope),
  FOREIGN KEY (audit_run_id) REFERENCES historical_quality_runs(audit_run_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_historical_quality_daily_date_scope
  ON historical_quality_daily(collection_date DESC, scope);

CREATE INDEX IF NOT EXISTS idx_historical_quality_daily_scope_score
  ON historical_quality_daily(scope, structural_score_v1, provenance_score_v1);
